language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - kssrcn@naver.com

before_deploy:
  - zip -r freeWebService *
  - mkdir -p deploy
  - mv freeWebService.zip deploy/freeWebService.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freewebservice-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-untill-deployed: true
#  - provider: codedeploy
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#    bucket: freewebservice-springboot-build
#    key: freeWebService.zip
#    bundle_type: zip
#    application: freeWebService
#    deployment_group: freeWebService-group
#    region: us-east-2
#    wait-untill-deployed: true

